name: keneya_muso
description: "Application de suivi santé maternelle et infantile"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Dépendances utilisées
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  flutter_speed_dial: ^7.0.0
  http: ^1.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  just_audio: ^0.9.34
  path_provider: ^2.1.1
  permission_handler: ^11.4.0
  shared_preferences: ^2.0.15
  video_player: ^2.8.6
  record: ^5.2.1
  path: ^1.9.0

dependency_overrides:
  record_linux: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/logo/